# --------------------- monitors -------------
monitor = , preferred, auto, 1

# --------------------- env (NVIDIA) ----------
env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = GBM_BACKEND,nvidia-drm
env = NVD_BACKEND,direct
env = ELECTRON_OZONE_PLATFORM_HINT,auto
env = MOZ_ENABLE_WAYLAND,1
env = QT_QPA_PLATFORM,wayland;xcb
env = SDL_VIDEODRIVER,wayland
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland

# Optional NVIDIA flicker fix:
# env = AQ_NO_ATOMIC,1

# ---------------------- autostart --------------
exec-once = /usr/lib/polkit-kde-authentication-agent-1
exec-once = waybar
exec-once = mako
exec-once = hyprpaper
exec-once = wl-paste --type text --watch cliphist store
exec-once =  wl-paste --type image --watch cliphist store

# ----------------------- input -------------------
input {
    kb_layout = us
    follow_mouse = 1
    sensitivity = 0
}

general {
    gaps_in = 4    
    gaps_out = 8
    border_size = 2
    layout = dwindle
}

decoration {
    rounding = 6

    blur { 
	enabled = true
	size = 4 
	passes = 2
	}
}

cursor {
    no_hardware_cursors = true # NVIDIA workaround for invisible cursor      
}

animations {
    enabled = yes
}

misc {
    disable_hyprland_logo = true
}


# ------------------------- keybinds ---------------------
$mod = SUPER
bind = $mod, Return, exec, alacritty
bind = $mod, Q, killactive
bind = $mod, M, exit
bind = $mod, V, togglefloating
bind = $mod, R, exec, wofi --show drun
bind = $mod, P, pseudo
bind = $mod, J, togglesplit

bind = $mod, left, movefocus, l
bind = $mod, right, movefocus, r
bind = $mod, up, movefocus, u
bind = $mod, down, movefocus, d

bind = $mod, 1, workspace, 1
bind = $mod, 2, workspace, 2
bind = $mod, 3, workspace, 3
bind = $mod, 4, workspace, 4
bind = $mod, 5, workspace, 5
bind = $mod SHIFT, 1, movetoworkspace, 1
bind = $mod SHIFT, 2, movetoworkspace, 2
bind = $mod SHIFT, 3, movetoworkspace, 3
bind = $mod SHIFT, 4, movetoworkspace, 4
bind = $mod SHIFT, 5, movetoworkspace, 5

bind = , Print, exec, grim -g "$(slurp)" - | wl-copy
bind = SHIFT, Print, exec, grim - | wl-copy

bindl = , XF86AudioMute, 	exec, pamixer -t
bindl = , XF86AudioRaiseVolume, exec, pamixer -i 5
bindl = , XF86AudioLowerVolume, exec, paxmier -d 5
bindl = , XF86AudioPlay, 	exec, playerctl play-pause
bindl = , XF86AudioNext,	exec, playerctl next
bindl = , XF86AudioPrev, 	exec, playerctl previous
